NumPy offers the random module to work with random numbers.

In [1]:
from numpy import random

In [4]:
x = random.randint(100)
print(x)

14


In [5]:
# The random module's rand() method returns a random float between 0 and 1.
x = random.rand()
print(x)

0.42578681740919655


In [6]:
# the randint() method takes a size parameter where you can specify the shape of an array.
x=random.randint(100, size=(5))
print(x)

[33 18 40 99 88]


In [7]:
x = random.randint(100, size=(3, 5))
print(x)

[[ 8 69 31 91 35]
 [27 45 30 62 13]
 [85  3 39 36 50]]


In [8]:
x = random.randint(999, size = (3,4,5))
print(x)

[[[ 44 986 745 852 119]
  [330 461 837 183 119]
  [799 825 973  30 593]
  [141 141 555 400  72]]

 [[927 320 885 784  26]
  [  9 534 829 845 570]
  [131 248 672 106 830]
  [564 453  53 244  43]]

 [[256  75 630 284  17]
  [626 231  48 499 142]
  [929 465 404 944  51]
  [327 180 950 800 703]]]


In [9]:
# The rand() method also allows you to specify the shape of the array.
x = random.rand(5)
print(x)

[0.91906563 0.28252965 0.62481876 0.70434985 0.04929793]


In [10]:
x = random.rand(5,4,3,2,1)
print(x)

[[[[[0.81554558]
    [0.81693445]]

   [[0.7868922 ]
    [0.5421143 ]]

   [[0.86056876]
    [0.68556029]]]


  [[[0.01943632]
    [0.25732227]]

   [[0.24335587]
    [0.29652722]]

   [[0.65360859]
    [0.62190701]]]


  [[[0.73559262]
    [0.86901067]]

   [[0.70806024]
    [0.57545613]]

   [[0.46090538]
    [0.35039102]]]


  [[[0.2287221 ]
    [0.63564849]]

   [[0.55226644]
    [0.35262735]]

   [[0.72526375]
    [0.42716583]]]]



 [[[[0.00334075]
    [0.25004372]]

   [[0.6179677 ]
    [0.63642626]]

   [[0.84653333]
    [0.64452575]]]


  [[[0.51783084]
    [0.25719449]]

   [[0.12007137]
    [0.54453449]]

   [[0.89370687]
    [0.3168137 ]]]


  [[[0.74769887]
    [0.93434933]]

   [[0.46346681]
    [0.21177678]]

   [[0.58149852]
    [0.9234341 ]]]


  [[[0.22863185]
    [0.98059368]]

   [[0.55036549]
    [0.95143497]]

   [[0.12418842]
    [0.72489077]]]]



 [[[[0.88931851]
    [0.4790886 ]]

   [[0.15400746]
    [0.36753525]]

   [[0.27196042]
    [0.33114158]]]


  [[[0

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

In [11]:
x = random.choice([3, 5, 7, 9])

print(x)

9


In [12]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 7 7 9 3]
 [5 5 5 9 3]
 [3 5 5 7 9]]
