In [1]:
from numpy import random

Random Distribution

A random distribution is a set of random numbers that follow a certain probability density function.

Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

The sum of all probability numbers should be 1.

In [3]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[5 5 7 5 7 7 7 5 7 3 7 7 3 7 5 7 7 5 7 7 7 7 5 3 7 5 7 5 7 7 7 5 7 3 5 7 3
 7 7 5 7 5 5 7 5 5 5 7 7 7 7 7 7 5 5 7 7 7 5 5 7 5 7 7 7 5 5 7 7 7 5 7 3 7
 3 5 5 5 7 5 7 5 3 5 5 3 7 7 7 7 7 5 3 7 7 7 7 7 5 7]


In [4]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[5 7 7 5 7]
 [5 7 7 7 5]
 [7 5 7 7 5]]
