In [3]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# import numpy library
import numpy as np

In [3]:
# check version
print(np.__version__)

2.1.3


In [4]:
# Create an numpy array
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [5]:
# type(): This built-in Python function tells us the type of the object passed to it.
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(5)
print(arr)

# If arr.shape gives (), it means that your NumPy array arr is a scalar—not a 1D, 2D, or higher-dimensional array.
print(arr.shape)

# ndim attribute that returns an integer that tells us how many dimensions the array have
print(arr.ndim)

5
()
0


In [19]:
# 1-D Arrays - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
arr = np.array([1, 2, 3, 4])
print(arr)

print(arr.shape)

# shape[i] refers to the size of the i-th dimension of an array
print(arr.shape[0])

print(arr.ndim)

[1 2 3 4]
(4,)
4
1


In [20]:
# 2-D Arrays - An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
print(arr)

print(arr.shape)
print(arr.shape[0])
print(arr.shape[1])

print(arr.ndim)

[[1 2 3 4]
 [4 3 2 1]]
(2, 4)
2
4
2


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

print(arr.shape)
print(arr.shape[0])
print(arr.shape[1])
print(arr.shape[2])

print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
2
2
3
3


In [22]:
# n-dimensional array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print(arr.shape)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
5


In [23]:
arr = np.array([[[[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]]], [[[1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4]]]])

print(arr)

print(arr.shape)
print(arr.ndim)

[[[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [1 2 3 4]]

  [[1 2 3 4]
   [1 2 3 4]]]]
(2, 2, 2, 4)
4


In [29]:
# Access Array Elements
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.
# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])

1
2
3
4


In [30]:
# Negative indexing - Use negative indexing to access an array from the end.
# -1 is the last element, -2 before the last and so on
print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])

4
3
2
1


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1][4])
print('2nd element on 1st row: ', arr[0, 1])

5th element on 2nd row:  10
2nd element on 1st row:  2


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0][1][2])

6
6


In [34]:
# Slicing arrays - Slicing in python means taking elements from one given index to another given index.
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [35]:
print(arr[4:])

[5 6 7]


In [36]:
print(arr[:4])

[1 2 3 4]


In [37]:
print(arr[-3:-1])

[5 6]


In [38]:
print(arr[1:5:2])

[2 4]


In [39]:
print(arr[::2])

[1 3 5 7]


In [40]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(arr[1, 1:4])

[7 8 9]


In [41]:
print(arr[0:2, 2])

[3 8]


In [42]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
